apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-hello-world
  template:
    metadata:
      labels:
        app: template-hello-world
    spec:
      containers:
      - name: hello-world
        image: hello-world:latest
        securityContext:
          runAsNonRoot: true
          runAsUser: 0
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
          seccompProfile:
            type: "RuntimeDefault"
        ports:
        - containerPort: 80
